name: lesgo_mobile_dev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-44.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  date_format: ^2.0.7
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  intl: ^0.17.0
  date_time_picker: ^2.1.0
  image_picker: ^0.8.6+1
  file_picker: ^5.2.5
  form_field_validator: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  environment_config: ^3.1.0

flutter: 
  uses-material-design: true

